"""empty message

Revision ID: ba9c3c892444
Revises: c7cb3ebf9fc1
Create Date: 2021-06-21 13:07:26.638233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9c3c892444'
down_revision = 'c7cb3ebf9fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_lag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logitude', sa.Float(precision=128), nullable=True),
    sa.Column('latitude', sa.Float(precision=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('log_lag')
    # ### end Alembic commands ###
