"""Initial migration.

Revision ID: c7cb3ebf9fc1
Revises: 
Create Date: 2021-06-11 11:26:31.172463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cb3ebf9fc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_lag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logitude', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_lag')
    # ### end Alembic commands ###
